# site settings
title: LGGJ
subtitle: Live Work
email: loreggjuc3m@gmail.com
description: About me
url: # the base hostname & protocol for your site
author: Lorena Gonzalez
street_address: Rio Duero
city: Madrid
state: Madrid
zip_code: 28911
country: Spain
phone: (34) 000 000 0000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8 #modify according necesities

# social settings
500px_url:
facebook_url:
github_url: https://github.com/lg-gonzalez-juarez
googleplus_url: https://plus.google.com/u/0/+LorenaGonzalezJuarez
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/lg-gonzalez-juarez
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
