# site settings
title: MyWeb
subtitle: biography
email: lorenita@gmail.com
description: Cosas de interes acerca de mi vida laboral
url: # the base hostname & protocol for your site
author:
street_address: 
city: Madrid
state: Madrid
zip_code: 28911
country: Spain
phone: (34) 00 000 0000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/lg-gonzalez-juarez
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+LorenaGonzalezJuarez
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/lg-gonzalez-juarez
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
